### ISSUE TITLE
create solr_index via REST-endpoint & update documentation (was: The solr_index field primary key "id" is not auto incrementing)

### ISSUE THREAD

**Issue by epugh** [pbartusch/smui#19]
The `solr_index` field has the primary key `id`, however it is not auto incrementing.  When you follow the instructions in the README, you don't insert an id, which causes SMUI ui to report an error.   

Changing

```
INSERT INTO solr_index (name, description) VALUES ('core_name1', 'Solr Search Index/Core');
```

to 
```
INSERT INTO solr_index (id, name, description) VALUES (1, 'core_name1', 'Solr Search Index/Core');
```

fixes it.  However, should the ID field be autoincrementing?

**Comment by epugh** [comment]
See PR #20 for the fix!

**Comment by pbartusch** [comment]
thanks @epugh ,

to make SMUI compatible to standard SQL, I removed `auto_increment` and made `id`s GUIDs. SMUI is used on top of several DBMS installations rights now (HSQL, mariaDB / mySQL, Postgres), so the `id` definition should be fine as is.

But I'll definitively check the documentation here and will provide a REST-endpoint to create the `solr_index` entities, so that a proper interface is provided here.

**Comment by pbartusch** [comment]
as discussed in #20 REST interfaces exist.
